# Generated by Django 5.2.7 on 2025-10-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='The unique code for the client group (e.g., AC, AP).', max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, help_text='The full name of the client group.', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTypeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='The unique code for this item.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='The description for this code.', max_length=255)),
            ],
            options={
                'ordering': ['description', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='The unique code for this item.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='The description for this code.', max_length=255)),
            ],
            options={
                'ordering': ['description', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrySubCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='The unique code for this item.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='The description for this code.', max_length=255)),
            ],
            options={
                'ordering': ['description', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, help_text='The unique account number for the client site.', max_length=50, unique=True)),
                ('name', models.CharField(help_text='The specific name of the client site.', max_length=255)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='address.address')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='organization.territory')),
                ('client_group', models.ForeignKey(help_text='The parent company for this client.', on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='client.clientgroup')),
                ('customer_type_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.customertypecode')),
                ('industry_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.industrycode')),
                ('industry_sub_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.industrysubcode')),
            ],
            options={
                'ordering': ['name', 'account_number'],
            },
        ),
    ]
