# Generated by Django 5.2.7 on 2025-10-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The unique code for the client group (e.g., AC, AP).', max_length=10, unique=True)),
                ('name', models.CharField(help_text='The full name of the client group (e.g., DOUGLAS HOME).', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
