# Generated by Django 5.2.7 on 2025-11-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_postalcode'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, help_text='The official, validated address for this client. This is the single source of truth for location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='address.address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address1',
            field=models.CharField(blank=True, help_text="LEGACY FIELD: Used for initial address validation. The source of truth is the 'address' field.", max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='address2',
            field=models.CharField(blank=True, help_text="LEGACY FIELD: Used for initial address validation. The source of truth is the 'address' field.", max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, help_text="LEGACY FIELD: Used for initial address validation. The source of truth is the 'address' field.", max_length=20),
        ),
    ]
