# Generated by Django 5.2.7 on 2025-10-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTypeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The unique code for this item.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='The description for this code.', max_length=255)),
            ],
            options={
                'ordering': ['description', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The unique code for this item.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='The description for this code.', max_length=255)),
            ],
            options={
                'ordering': ['description', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrySubCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The unique code for this item.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='The description for this code.', max_length=255)),
            ],
            options={
                'ordering': ['description', 'code'],
                'abstract': False,
            },
        ),
    ]
