# Generated by Django 5.2.7 on 2025-10-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_status_data'),
        ('client', '0002_client_address1_client_address2_client_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='address.addressstatus'),
        ),
    ]
