# Generated by Django 5.2.7 on 2025-10-23 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_customertypecode_industrycode_industrysubcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The unique code for this item.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='The description for this code.', max_length=255)),
            ],
            options={
                'ordering': ['description', 'code'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='name',
            field=models.CharField(help_text='The full name of the client group.', max_length=255),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='The unique account number for the client site.', max_length=50, unique=True)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('client_group', models.ForeignKey(help_text='The parent company for this client.', on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='client.clientgroup')),
                ('customer_type_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.customertypecode')),
                ('industry_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.industrycode')),
                ('industry_sub_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.industrysubcode')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.territory')),
            ],
            options={
                'ordering': ['account_number'],
            },
        ),
    ]
