# Generated by Django 5.2.7 on 2025-10-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_address_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='territory',
        ),
    ]
