# Generated by Django 5.2.7 on 2025-10-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_territory_alter_clientgroup_name_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(db_index=True, help_text='The unique account number for the client site.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='code',
            field=models.CharField(db_index=True, help_text='The unique code for the client group (e.g., AC, AP).', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='name',
            field=models.CharField(db_index=True, help_text='The full name of the client group.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customertypecode',
            name='code',
            field=models.CharField(db_index=True, help_text='The unique code for this item.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='industrycode',
            name='code',
            field=models.CharField(db_index=True, help_text='The unique code for this item.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='industrysubcode',
            name='code',
            field=models.CharField(db_index=True, help_text='The unique code for this item.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='territory',
            name='code',
            field=models.CharField(db_index=True, help_text='The unique code for this item.', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['address1'], name='client_clie_address_b26ad5_idx'),
        ),
    ]
