# Generated by Django 5.2.7 on 2025-10-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_account_number_alter_clientgroup_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name', 'account_number']},
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='allo', help_text='The specific name of the client site.', max_length=255),
            preserve_default=False,
        ),
    ]
