# Generated by Django 5.2.7 on 2025-10-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_client_territory'),
        ('organization', '0003_alter_territory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='organization.territory'),
        ),
    ]
