# Generated by Django 5.2.7 on 2025-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCostParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default='Default Travel Costs', max_length=100)),
                ('cost_per_minute', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('cost_per_km', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('truck_depreciation_fixed_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('supply_charge_fixed_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Travel Cost Parameters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(choices=[('PROVINCE', 'Province'), ('REGION', 'Regional Municipality'), ('CITY', 'City')], db_index=True, max_length=20)),
                ('boundary_geojson', models.JSONField(blank=True, help_text="GeoJSON representation of the territory's boundary.", null=True)),
                ('fsas', models.ManyToManyField(blank=True, help_text='The FSAs that define this territory.', related_name='territories', to='address.fsa')),
            ],
            options={
                'verbose_name_plural': 'Territories',
                'ordering': ['type', 'name'],
                'unique_together': {('name', 'type')},
            },
        ),
    ]
