# Generated by Django 5.2.7 on 2025-10-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='territory',
            options={'ordering': ['type', 'name'], 'verbose_name_plural': 'Territories'},
        ),
        # AlterUniqueTogether has been removed from this migration
        migrations.AddField(
            model_name='territory',
            name='name',
            field=models.CharField(db_index=True, default='temporary', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='territory',
            name='type',
            field=models.CharField(choices=[('PROVINCE', 'Province'), ('REGION', 'Regional Municipality'), ('CITY', 'City')], db_index=True, default='temporary', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='territory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='description',
        ),
    ]
