# Generated by Django 5.2.7 on 2025-10-29 12:46

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NestedTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="The name of the territory (e.g., 'Canada', 'Quebec', 'Montreal', 'H2X', 'H2X 1X6').", max_length=255)),
                ('type', models.CharField(choices=[('COUNTRY', 'Country'), ('PROVINCE', 'Province'), ('REGION', 'Regional Municipality'), ('CITY', 'City'), ('FSA', 'Forward Sortation Area'), ('POSTAL_CODE', 'Postal Code'), ('ADDRESS', 'Specific Address')], db_index=True, max_length=20)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.nestedterritory')),
                ('source_address', models.OneToOneField(blank=True, help_text='Link to the original address.Address object (only for ADDRESS type nodes).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_territory_node', to='address.address')),
            ],
            options={
                'verbose_name': 'Nested Territory',
                'verbose_name_plural': 'Nested Territories',
                'unique_together': {('parent', 'name', 'type')},
            },
        ),
    ]
