# Generated by Django 5.2.7 on 2025-10-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_territory_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='territory',
            unique_together={('name', 'type')},
        ),
    ]
