# Generated by Django 5.2.7 on 2025-10-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_nestedterritory'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestedterritory',
            name='client_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of clients in this territory and all its descendants.'),
        ),
    ]
