# Generated by Django 5.2.7 on 2025-10-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_territory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='boundary_geojson',
            field=models.JSONField(blank=True, help_text="GeoJSON representation of the territory's boundary.", null=True),
        ),
    ]
