# Generated by Django 5.2.7 on 2025-10-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_nestedterritory_client_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nestedterritory',
            name='level',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='nestedterritory',
            name='lft',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='nestedterritory',
            name='rght',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='nestedterritory',
            name='tree_id',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
