# Generated by Django 5.2.7 on 2025-10-31 11:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_nestedterritory_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestedterritory',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='The geographical boundary of the territory.', null=True, srid=4326),
        ),
    ]
