# Generated by Django 5.2.7 on 2025-10-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_nestedterritory_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestedterritory',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='An official code for the territory, like a CDUID or PRUID.', max_length=50, null=True),
        ),
    ]
