# Generated by Django 5.2.7 on 2025-10-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_nestedterritory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestedterritory',
            name='scraped_data',
            field=models.JSONField(blank=True, help_text='Raw data scraped from external sources like Wikipedia.', null=True),
        ),
    ]
