# Generated by Django 5.2.7 on 2025-10-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_nestedterritory_scraped_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestedterritory',
            name='boundary_status',
            field=models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('MATCHED', 'Matched'), ('NO_SHAPEFILE_MATCH', 'No Shapefile Match'), ('NEEDS_WIKI_SCRAPE', 'Needs Wiki Scrape'), ('WIKI_SCRAPED', 'Wiki Scraped'), ('MANUAL_REVIEW', 'Manual Review Needed')], db_index=True, default='UNPROCESSED', max_length=20),
        ),
    ]
