# Generated by Django 5.2.7 on 2025-11-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_nestedterritory_boundary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestedterritory',
            name='tree_name',
            field=models.CharField(db_index=True, default='Default', help_text="The name of the hierarchy this node belongs to (e.g., 'Electoral', 'Administrative').", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='nestedterritory',
            unique_together={('tree_name', 'parent', 'name', 'type')},
        ),
        migrations.RemoveField(
            model_name='nestedterritory',
            name='source_address',
        ),
    ]
