# Generated by Django 5.2.7 on 2025-11-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_nestedterritory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nestedterritory',
            unique_together=set(),
        ),
    ]
