# Generated by Django 5.2.7 on 2025-11-05 20:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_nestedterritory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestedterritory',
            name='simplified_boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Pre-calculated simplified boundary for quick rendering at low zoom levels.', null=True, srid=4326),
        ),
    ]
