# Generated by Django 5.2.7 on 2025-10-22 18:00

from django.db import migrations

def create_groups(apps, schema_editor):
    """Creates the initial employee groups."""
    Group = apps.get_model('auth', 'Group')
    
    groups_to_create = [
        'Directors',
        'Managers',
        'Technicians',
        'Dispatchers',
    ]
    
    for group_name in groups_to_create:
        Group.objects.get_or_create(name=group_name)

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'), # This depends on your first migration
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
