# Generated by Django 5.2.7 on 2025-11-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_fsa_boundary_type_fsa_source'),
        ('employees', '0001_initial'),
        ('organization', '0011_nestedterritory_simplified_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text="The employee's home postal code. Used as a starting point for location and distance calculations.", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='responsible_fsas',
            field=models.ManyToManyField(blank=True, help_text='FSAs a Technician is directly responsible for.', related_name='technicians', to='address.fsa'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='territories',
            field=models.ManyToManyField(blank=True, help_text='Legacy field for manager-level territory assignments.', related_name='employees', to='organization.territory'),
        ),
    ]
