# Generated by Django 5.2.7 on 2025-11-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_postalcode'),
        ('employees', '0002_employeeprofile_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='postal_code',
            field=models.ForeignKey(blank=True, help_text="The employee's home postal code. Used as a starting point for location and distance calculations.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.postalcode'),
        ),
    ]
