# Generated by Django 5.2.7 on 2025-11-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeeprofile_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianFSAStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsa_code', models.CharField(help_text='FSA code from the CSV.', max_length=3)),
                ('technician_code', models.CharField(help_text='Technician code from the CSV.', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('ERROR', 'Error'), ('IGNORED', 'Ignored')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technician FSA Staging Record',
                'verbose_name_plural': 'Technician FSA Staging Records',
                'ordering': ['created_at'],
            },
        ),
    ]
