# Generated by Django 5.2.7 on 2025-11-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_postal_code', models.CharField(db_index=True, max_length=10)),
                ('destination_address_id', models.PositiveIntegerField(db_index=True)),
                ('distance_metres', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cached Route',
                'verbose_name_plural': 'Cached Routes',
                'unique_together': {('origin_postal_code', 'destination_address_id')},
            },
        ),
    ]
