# Generated by Django 5.2.7 on 2025-10-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted', models.CharField(blank=True, max_length=255, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('street_number', models.CharField(blank=True, max_length=50, null=True)),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('administrative_area_level_1', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='The unique code for this FSA.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='A description for this FSA (e.g., city/region).', max_length=255)),
            ],
            options={
                'verbose_name': 'FSA',
                'verbose_name_plural': 'FSAs',
                'ordering': ['code'],
            },
        ),
    ]
