# Generated by Django 5.2.7 on 2025-10-29 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatted', models.CharField(blank=True, max_length=255, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('badge_class', models.CharField(default='bg-secondary', help_text="Bootstrap badge class, e.g., 'bg-success', 'bg-warning text-dark', 'bg-danger'.", max_length=50)),
            ],
            options={
                'verbose_name': 'Address Status',
                'verbose_name_plural': 'Address Statuses',
            },
        ),
        migrations.CreateModel(
            name='FSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='The unique code for this FSA.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='A description for this FSA (e.g., city/region).', max_length=255)),
            ],
            options={
                'verbose_name': 'FSA',
                'verbose_name_plural': 'FSAs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AddressValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clients_complete', models.PositiveIntegerField(default=0)),
                ('clients_incomplete', models.PositiveIntegerField(default=0)),
                ('clients_missing', models.PositiveIntegerField(default=0)),
                ('employees_complete', models.PositiveIntegerField(default=0)),
                ('employees_incomplete', models.PositiveIntegerField(default=0)),
                ('employees_missing', models.PositiveIntegerField(default=0)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address Validation Log',
                'verbose_name_plural': 'Address Validation Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
