# Generated by Django

from django.db import migrations

def create_initial_statuses(apps, schema_editor):
    AddressStatus = apps.get_model('address', 'AddressStatus')
    AddressStatus.objects.bulk_create([
        AddressStatus(name='COMPLETE', description='A complete, rooftop-level address.', badge_class='bg-success'),
        AddressStatus(name='INCOMPLETE', description='An address missing critical components (street, city, or postal code). It is not serviceable.', badge_class='bg-warning text-dark'),
        AddressStatus(name='MISSING', description='No address is assigned.', badge_class='bg-danger'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'), # Make sure this matches your previous migration
    ]

    operations = [
        migrations.RunPython(create_initial_statuses),
    ]
