# Generated by Django 5.2.7 on 2025-10-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('badge_class', models.CharField(default='bg-secondary', help_text="Bootstrap badge class, e.g., 'bg-success', 'bg-warning text-dark', 'bg-danger'.", max_length=50)),
            ],
            options={
                'verbose_name': 'Address Status',
                'verbose_name_plural': 'Address Statuses',
            },
        ),
    ]
