# Generated by Django

from django.db import migrations, models

def create_initial_statuses(apps, schema_editor):
    AddressStatus = apps.get_model('address', 'AddressStatus')
    AddressStatus.objects.bulk_create([
        AddressStatus(name='COMPLETE', description='A complete, rooftop-level address.', badge_class='bg-success'),
        AddressStatus(name='INCOMPLETE', description='An address missing critical components (street, city, or postal code). It is not serviceable.', badge_class='bg-warning text-dark'),
        AddressStatus(name='MISSING', description='No address is assigned.', badge_class='bg-danger'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('badge_class', models.CharField(default='bg-secondary', help_text="Bootstrap badge class, e.g., 'bg-success', 'bg-warning text-dark', 'bg-danger'.", max_length=50)),
            ],
            options={
                'verbose_name': 'Address Status',
                'verbose_name_plural': 'Address Statuses',
            },
        ),
        migrations.RunPython(create_initial_statuses),
    ]
