# Generated by Django 5.2.7 on 2025-10-31 14:00

from django.db import migrations
from django.contrib.gis.geos import Point

def populate_locations(apps, schema_editor):
    """
    Iterate through all existing Address objects and populate the new
    `location` PointField from the existing `latitude` and `longitude` fields.
    """
    Address = apps.get_model('address', 'Address')
    
    # We only need to process addresses that have lat/lon but no location point yet.
    addresses_to_update = Address.objects.filter(
        latitude__isnull=False, 
        longitude__isnull=False, 
        location__isnull=True
    )

    # Use bulk_update for efficiency. It's safer for large datasets.
    # We create a list of objects to update first.
    updated_objects = []
    for address in addresses_to_update.iterator(chunk_size=2000):
        # Note: Point constructor takes (x, y), which corresponds to (longitude, latitude)
        address.location = Point(float(address.longitude), float(address.latitude), srid=4326)
        updated_objects.append(address)

    if updated_objects:
        Address.objects.bulk_update(updated_objects, ['location'], batch_size=2000)
        print(f"\nUpdated the location for {len(updated_objects)} addresses.")

def reverse_populate_locations(apps, schema_editor):
    """Reverts the change, setting all location fields to NULL."""
    Address = apps.get_model('address', 'Address')
    Address.objects.update(location=None)


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_location'), # This migration runs after the location field is added
    ]

    operations = [
        migrations.RunPython(populate_locations, reverse_code=reverse_populate_locations),
    ]
