# Generated by Django 5.2.7 on 2025-10-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_addressstatus'),
        ('address', '0002_create_address_statuses'),
    ]

    operations = [
    ]
