# Generated by Django 5.2.7 on 2025-10-26 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_status_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clients_complete', models.PositiveIntegerField(default=0)),
                ('clients_incomplete', models.PositiveIntegerField(default=0)),
                ('clients_missing', models.PositiveIntegerField(default=0)),
                ('employees_complete', models.PositiveIntegerField(default=0)),
                ('employees_incomplete', models.PositiveIntegerField(default=0)),
                ('employees_missing', models.PositiveIntegerField(default=0)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address Validation Log',
                'verbose_name_plural': 'Address Validation Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
