# Generated by Django 5.2.7 on 2025-10-31 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_populate_locations_from_latlon'),
        ('organization', '0008_nestedterritory_boundary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code_node',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'POSTAL_CODE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses_linked', to='organization.nestedterritory'),
        ),
    ]
