# Generated by Django 5.2.7 on 2025-11-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_address_postal_code_node'),
        ('organization', '0009_alter_nestedterritory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postal_code_node',
        ),
        migrations.AddField(
            model_name='address',
            name='territories',
            field=models.ManyToManyField(blank=True, help_text='Links this address to all relevant territory nodes (e.g., its Postal Code, its FED, its City).', related_name='addresses', to='organization.nestedterritory'),
        ),
    ]
