# Generated by Django 5.2.7 on 2025-10-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_addressvalidationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='administrative_area_level_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='administrative_area_level_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='sublocality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
