# Generated by Django 5.2.7 on 2025-10-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_address_administrative_area_level_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='administrative_area_level_1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='administrative_area_level_2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='administrative_area_level_3',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='route',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='sublocality',
        ),
    ]
