# Generated by Django 5.2.7 on 2025-11-03 19:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_remove_address_postal_code_node_address_territories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fsa',
            options={'ordering': ['code'], 'verbose_name': 'Forward Sortation Area (FSA)', 'verbose_name_plural': 'Forward Sortation Areas (FSAs)'},
        ),
        migrations.AddField(
            model_name='fsa',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='The geographic boundary of the FSA.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='fsa',
            name='census_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='The census year the data is from (e.g., 2021).', null=True),
        ),
        migrations.AddField(
            model_name='fsa',
            name='cfsa_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Census Forward Sortation Area Unique Identifier (CFSAUID).', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fsa',
            name='land_area',
            field=models.FloatField(blank=True, help_text='Land area in square kilometers.', null=True),
        ),
        migrations.AddField(
            model_name='fsa',
            name='pruid',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier for the province or territory (PRUID).', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='fsa',
            name='code',
            field=models.CharField(db_index=True, help_text='The 3-character Forward Sortation Area code (e.g., H2X).', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='fsa',
            name='description',
            field=models.CharField(blank=True, help_text='A description for this FSA, which may be imported from external sources.', max_length=255),
        ),
    ]
