# Generated by Django 5.2.7 on 2025-11-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_alter_fsa_options_fsa_boundary_fsa_census_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsa',
            name='cfsa_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Census Forward Sortation Area Unique Identifier (CFSAUID), which is the IDUGD.', max_length=21, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fsa',
            name='pruid',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier for the province or territory (PRUID).', max_length=2, null=True),
        ),
    ]
