# Generated by Django 5.2.7 on 2025-11-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_alter_fsa_cfsa_uid_alter_fsa_pruid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsa',
            name='client_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total number of active clients in this FSA.'),
        ),
    ]
