# Generated by Django 5.2.7 on 2025-11-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_fsa_client_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsa',
            name='boundary_type',
            field=models.CharField(blank=True, choices=[('OFFICIAL', 'Official Census Boundary'), ('INFERRED_CONVEX_HULL', 'Inferred from Client Points (Convex Hull)')], db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fsa',
            name='source',
            field=models.CharField(choices=[('CENSUS', 'From Statistics Canada Census'), ('INFERRED', 'Inferred from Client Data')], db_index=True, default='CENSUS', max_length=20),
        ),
    ]
