# Generated by Django 5.2.7 on 2025-11-13 19:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_fsa_boundary_type_fsa_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsa',
            name='simplified_boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='A pre-calculated, low-resolution version of the boundary for fast map rendering.', null=True, srid=4326),
        ),
    ]
