# Generated by Django 5.2.7 on 2025-11-14 15:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_fsa_simplified_boundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='The 6 or 7-character postal code (e.g., H2X1X6).', max_length=7, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The geocoded point for this postal code.', null=True, srid=4326)),
                ('last_geocoded', models.DateTimeField(blank=True, help_text='When the postal code was last geocoded.', null=True)),
            ],
            options={
                'verbose_name': 'Postal Code',
                'verbose_name_plural': 'Postal Codes',
                'ordering': ['code'],
            },
        ),
    ]
