# Generated by Django 5.2.7 on 2025-11-14 17:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_postalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsa',
            name='center_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The geographic center (centroid) of the FSA, often from a geocoding service.', null=True, srid=4326),
        ),
    ]
